sudo: required
dist: trusty
language: cpp
compiler: 
    - g++

python:
    - "2.7"

cache:
    directories:
        - "~/.libmath"

install:
    - sudo apt-get -y install python-pip python-dev
    - sudo pip install -U platformio
    - sudo platformio update
    - sudo pio lib install "RadioHead"

script:
    - sudo platformio ci app_mega/src --board=megaatmega2560 --lib="." 
    - cd ./app_common/
    - sudo make 
    - cd ./bin/
    - sudo ./test_*

notifications:
  email:
    on_success: change
    on_failure: change
