sudo: required
dist: trusty
language: cpp
compiler: 
    - g++

python:
    - "2.7"

cache:
    directories:
        - "~/.libmath"

install:
    - sudo apt-get -y install python-pip python-dev
    - sudo pip install -U platformio
    - sudo platformio update

script:
    - sudo platformio ci app_mega/src --board=megaatmega2560 --lib="." --lib="app_mega/lib/" --lib="app_mega/lib/AdafruitRadioHead"
    - sudo platformio ci app_uno/src --board=uno --lib="." --lib="app_uno/lib/" --lib="app_uno/lib/AdafruitRadioHead"
    - cd ./app_common/
    - sudo make 
    - cd ./bin/
    - sudo ./test_*

notifications:
  email:
    on_success: change
    on_failure: change
